### ISSUE TITLE
Install looks broken

### ISSUE THREAD

**Issue by Godley** [vadimdemedes/pronto#3]
I ran `npm install --global vadimdemedes/pronto` - I'm on MacOS high sierra node v6.9.1

then tried the `pronto` command and got:
```
/usr/local/lib/node_modules/pronto/cli.js:45
const askForToken = async () => {
                          ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

is there some older version that's not broken? Can't see tags in git so guess it's manually deployed. I see the last commit was "pin to version 7", which I suspect might be the problem, but there's no mention of that in the readme.

**Comment by vadimdemedes** [comment]
Pronto requires Node.js v8.x or higher to work. If you install that, it should work as expected.

**Comment by Godley** [comment]
Right, can you please put that in the readme?

**Comment by vadimdemedes** [comment]
It's in the package.json (https://github.com/vadimdemedes/pronto/blob/master/package.json#L13-L15), so npm/yarn should show a warning when you have an incompatible version of Node.
