### ISSUE TITLE
not feeling much the experience..

### ISSUE THREAD

**Issue by akabab** [vadimdemedes/pronto#4]
```
❯ pronto
? Select a database to deploy: MySQL
⠼ Deploying MySQLHTTPError: Response code 422 (Unprocessable Entity)
    at stream.catch.then.data (/usr/local/lib/node_modules/pronto/node_modules/got/index.js:182:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)

```

**Comment by vadimdemedes** [comment]
Could you paste the actual response? You will need to `try..catch` this https://github.com/vadimdemedes/pronto/blob/master/cli.js#L116 and log `err.res.body`.

**Comment by akabab** [comment]
```
❯ ./cli.js
? Select a database to deploy: MySQL
⠙ Deploying MySQL{ HTTPError: Response code 422 (Unprocessable Entity)
    at stream.catch.then.data (/Users/ycribier/pronto/node_modules/got/index.js:182:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
  name: 'HTTPError',
  host: 'api.compose.io',
  hostname: 'api.compose.io',
  method: 'POST',
  path: '/2016-07/deployments',
  protocol: 'https:',
  url: 'https://api.compose.io/2016-07/deployments',
  statusCode: 422,
  statusMessage: 'Unprocessable Entity',
  headers:
   { date: 'Mon, 16 Apr 2018 16:26:56 GMT',
     connection: 'close',
     'x-frame-options': 'SAMEORIGIN',
     'x-xss-protection': '1; mode=block',
     'x-content-type-options': 'nosniff',
     server: 'ComposeAPI/2016-07',
     'content-type': 'application/json; charset=utf-8',
     'cache-control': 'no-cache',
     'x-request-id': '25ABA7F99AC2_0A00000220FB_5AD4CED0_06E516C4',
     'x-runtime': '0.043162',
     vary: 'Accept-Encoding, Origin',
     'content-encoding': 'gzip',
     'strict-transport-security': 'max-age=31536000' } }
✔ Deployed
TypeError: Cannot read property 'ca_certificate_base64' of undefined
    at main (/Users/ycribier/pronto/cli.js:122:43)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

**`Cannot read property 'ca_certificate_base64' of undefined`**

**Comment by akabab** [comment]
how can I add a new token through the cli ?

**Comment by vadimdemedes** [comment]
Pronto should've asked for Compose token automatically, did it not? Btw, I don't see a response body here, could you try logging `err.response.body`, like here: https://github.com/sindresorhus/got#usage?

**Comment by akabab** [comment]
it did with the globally npm installed one, but with the cloned repo, it didn't, I suppose you save the config somewhere. I revoked the token from the compose interface so..

**Comment by akabab** [comment]
it finally got deployed, idk, maybe a problem authenticating. btw I deleted the `~/.config/configstore/pronto.json` file so it prompted me for a new token

**Comment by vadimdemedes** [comment]
Yeah, sounds right, it was related to the token.
